### ISSUE TITLE
initial `oldLocation = readLocation` happens too early

### ISSUE THREAD

**Issue by misantronic** [basarat/takeme#11]
when using html5-routing, the initial `let oldLocation = readLocation()` happens too early. It is called before `dom.html5Base` isset, so readLocation will always fall back to `if (html5Base == null) {`.
A fix would be to call `oldLocation = readLocation()` in the `init()` function (which makes more sense than calling it initially)

**Comment by basarat** [comment]
Released `0.12.0` :rose:
