### ISSUE TITLE
Thank you and a question on... nested routes

### ISSUE THREAD

**Issue by carlosagsmendes** [basarat/takeme#2]
Hi @basarat, thank you for sharing this project.

I was reading the docs and you mention the following right in the beginning:

> Why not any nesting routes?
> You can map url => state => any arbitrary nesting of components very easily and more maintainably in the long term instead of depending on hidden features of some library.

<img width="436" alt="nested" src="https://user-images.githubusercontent.com/1224078/36455444-f97bef30-1697-11e8-8466-ef9bf2884b6e.png">

Imagine that when I navigate to Dave or John's profile I need to have two nested routes (posts and details):

http://basarat.com/takeme-demo/awesome/profile/dave/posts
http://basarat.com/takeme-demo/awesome/profile/dave/details
 
Can you share an example or some guidance on how to achieve nested routing?

Thanks in advance

**Comment by basarat** [comment]
> thank you for sharing this project.

Thank you for having a look :rose:

> Can you share an example or some guidance on how to achieve nested routing?

Going through : http://basarat.com/takeme/#/?id=complete-example-walkthrough and accommodating requirements, changes are exactly where you would expect them (links, state, link->state config, Page) :rose:

```js
// Links
export const links = {
  login: () => '/login',
  profile: (id: string) => `/profile/${id}`,
  posts: (id: string) => `/profile/${id}/posts`,
  details: (id: string) => `/profile/${id}/details`,
}
//  State 
export type Route = 'login' | 'profile' | 'posts' | 'details';
export class RouteState {
  @observable route: Route = 'login';
  // ... so on 
}
const routeState = new RouteState();
// URL -> State 
const ensureLogin = () => {
  if (!routeState.loggedIn) {
    routeState.setLoginRequiredMessage('You need to login before you can visit a profile page');
    return { redirect: links.login() };
  }
}
export const router = new Router([
  {
    $: links.login(),
    enter: () => routeState.setRoute('login')
  },
  {
    $: links.profile(':profileId'),
    enter: ({ params: { profileId } }) => {
      routeState.setRoute('profile');
      routeState.setProfile(profileId);
    },
    beforeEnter: ensureLogin,
  },
  {
    $: links.posts(':profileId'),
    enter: ({ params: { profileId } }) => {
      routeState.setRoute('posts');
      routeState.setProfile(profileId);
    },
    beforeEnter: ensureLogin,
  },
  // ... so on 
  { $: '*', enter: () => routeState.setRoute('login') },
]).init();

// State -> Page 
const Page = observer(() => {
  switch (routeState.route) {
    case 'login': return <Login />;
    case 'profile': return <Profile profileId={routeState.profileId} />
    case 'posts': return <Posts profileId={routeState.profileId} />
    // ... so on
    default:
      const _ensure: never = routeState.route;
      return <noscript />
  }
});

```

**Comment by thupi** [comment]
Hi, very interesting and simple solution for something that used to be quite complicated :-) 

I was wondering is nested routers could be implemented :-) 

Let's say the details page mentions above should have some kind of tabs that could switch between sections. 

Would I be possible to put a switch statements in there too and have some kind of nested routers :-) ?

**Comment by basarat** [comment]
> Let's say the details page mentions above should have some kind of tabs that could switch between sections.

Create a simple / easy to maintain and test component e.g. 

```js
const SharedNav = () =>  (<div> Insert component logic here </div>); 

const Profile = observer(() => {
   return (
       <> 
          <div>Profile</div>
          <SharedNav/>
       </>
   );
});
const Posts = observer(() => {
   return (
       <> 
          <div>Posts</div>
          <SharedNav/>
       </>
   );
});
```
:rose:

**Comment by thupi** [comment]
@basarat Ahh, okay :-) 

But the logic i kind have a hard time figuring out is the switch statement that somhow needs to match only the child of profiles :-) 

Component Tree:
Root -> Router -> Profile -> ProfileRouter -> ProfileDetails

So the ProfileRouter is just a switch statement as with the root Router. But that router must only match routes the are considered child routes of '/profile/:profileId' :-) That way i would be able to have a Router that handles the tabs i was mentiond earlier :-)

In the samples there is used a string such as 'login' or 'profile' in order to determine the current route. However this might not be suitable for nested Routers. I was wondering if something like [router5](https://github.com/router5/router5) could be accomplished with the use of mobx reactivity and the state based approch to routing :-)

Hope this makes sense :-)

**Comment by basarat** [comment]
`Root -> Router -> Profile -> ProfileRouter -> ProfileDetails` I think you are forcing a solution for the problem that can be solved otherwise (with component composition).

**Comment by thupi** [comment]
I have a deeply nested navigation tree in one of my projects and like the nested router way of organizing applications routes and code splitting and so on :-)

Thanks for the quick answer :-)
