### ISSUE TITLE
Common animation pitfalls?

### ISSUE THREAD

**Issue by RickCarlino** [basarat/takeme#8]
First off, thanks for creating this great router. I really love the simplicity of it.

We are currently transitioning away from `react-router` v3. One part of the application relied on child routes heavily.

While performing the upgrade, I noticed that animations are now firing too frequently. It is only happening in places that previously used child routes. All other animations (on pages that don't have child routes) work. 

Here's a screen grab of what's happening:
[New Behavior (unexpected)](https://imgur.com/a/CmOpL0U)
[Old Behavior (expected)](https://imgur.com/a/Ulx3YyN)

Notice the excessive firing between panel flips in the first example.

Notes:
 * We don't use `react-transition-group` in the project directly and all animations are pure CSS.
 * We currently set the `children` prop at runtime in the router's `onEnter` hook using local state.

So my question is: **are there any common pitfalls with CSS animations within `props.children`?** 

Possibly relevant discussions for anyone who is in a similar situation: https://github.com/basarat/takeme/issues/2

Thanks again for this great lib! Really appreciate all the hard work that went into it.

**Comment by basarat** [comment]
> Notice the excessive firing between panel flips in the first example.

Simple case of dom recreation. React is *recreating* the `Tomatoes` on state switch. Try and preserve the component across state changes. e.g. 

* Bad: 

```
App
  Children switch on state: 
 -> FarmEvents renders Tomatoes
 -> Plants renders Tomatoes
```
* Better (probably but check the docs ... and compare with your code ... quick google search https://www.google.com.au/search?q=react+prevent+dom+recreation)

```
App 
  Children switch on state
 -> FarmEvents
   -> pass children Tomatoes
 -> Plants 
   -> pass children Tomatoes
```

Closing. This is indeed a common pitfall ... but a pitfall of react :rose:

**Comment by RickCarlino** [comment]
Thanks, @basarat!
